name: Python CI

on:
  push:
  pull_request:

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium script (headless)
        env:
          CI: 'true'
        run: |
          python google_search_selenium.py

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: search_results
          path: search_results.png
          if-no-files-found: warn

